### ISSUE TITLE
Rename Custom JS Variable error + doesn't propagate new name in the other container objects

### ISSUE THREAD

**Issue by lneuville** [matomo-org/tag-manager#552]
Hi guys,

I've experienced a rather painful issue that I've reproduced, so I beleive it's the right place to share it... It may be a bug, or at minima a wording issue in displayed messages ;

Here are the steps :

- context : Matomo Cloud

1 - I have a Custom JS variable that I use in all my Triggers. 

![trigger-initial-state-with-variable-name1](https://user-images.githubusercontent.com/46717153/194519347-080f2516-a437-4203-ae56-fc24c663b907.jpg)

2 - In order to give it a more meaningful name, I simply renamed it. Adding 'TEST' in the name, and then submit the change. 

![variable-rename-adding-test-in-name](https://user-images.githubusercontent.com/46717153/194519506-73c5f3b4-656b-4ca1-8382-ad97a9e0f576.jpg)

3 - Here I got an error message... regarding an Event Name that must be provided... I didn't understand why :

![variable-rename-error](https://user-images.githubusercontent.com/46717153/194519734-ee7c8c5f-0784-4158-a1cc-a77493b32cce.jpg)

4 - Then I re-submit the change... this time I have a 'OK-success' message : 

![variable-rename-re-submit-ok](https://user-images.githubusercontent.com/46717153/194520183-c606c50e-5525-4a34-852f-df68d30d3ca6.jpg)

5 - But when I check my Trigger with the Variable name, it didn't update (the 'TEST' bit is missing).

![trigger-with-variable-name-not-changed-to-new-name](https://user-images.githubusercontent.com/46717153/194520288-cf99c059-73d4-49e8-8363-63d75084fad1.jpg)

Thanks for taking a look.

Best regards

Laurent

**Comment by snake14** [comment]
Hi @lneuville . Thank you for taking the time to create this issue. Which version of Matomo are you currently using? Matomo version 4.12 was recently released and this sounds very similar to [an issue that I fixed as part of that release](https://github.com/matomo-org/tag-manager/issues/314). If possible, please upgrade to Matomo version 4.12 and let me know if the issue persists. I'm going to mark this issue as closed, but please feel free to let me know if you think it should be re-opened.

**Comment by lneuville** [comment]
Hi @snake14 . Thanks for you're feedback. 
Sorry I wasn't mentioned clearly enough on my post ; It was on Matomo Cloud. So I don't really know which version number is currently running on the cloud service.

**Comment by AltamashShaikh** [comment]
@lneuville You can check this [FAQ](https://matomo.org/faq/how-to/how-do-i-know-which-version-of-matomo-i-am-using/#matomocloud) to find out which version you are on cloud.

**Comment by lneuville** [comment]
Ok, It says 4.12.
So I as I reproduced it with the steps described in my first post, I would say the issue is still here.

**Comment by snake14** [comment]
@lneuville How long ago did you validate your issue? I only ask because version 4.12 was released mid-week last week and I think it usually takes a few days for cloud to be upgraded. It's possible you tested the issue just before cloud was upgraded. Could you please quickly verify one more time that the issue still exists?

**Comment by snake14** [comment]
@lneuville I didn't hear back. Does that mean that things are working correctly now? I tried to reproduce the issue in my local environment, but the variable was correctly renamed in the referencing trigger when I renamed the variable. I'm going to go ahead and close this issue again. Please let me know if you're still experiencing the issue.

**Comment by lneuville** [comment]
Hi  @snake14 
Just tried again. And reproduced.
I also tried another type of Variable (Datalayer variable) and experienced the same issue.

**Comment by snake14** [comment]
@lneuville That is so strange. I apologise for this continued issue. Are there any errors logged around the time that you try to update the variable name?

Just to be absolutely sure, could you please check what version of Matomo is listed in your instance? You can do that, while logged into Matomo, by going to Administration (Gear icon) > Diagnostic > System Check ({your matomo base url}`/index.php?module=Installation&action=systemCheckPage`) and scrolling down to the Information results section, which should look something like this:
![image](https://user-images.githubusercontent.com/11394099/195705468-19b5e29a-c422-4f8d-b823-4f5103bae281.png)

**Comment by lneuville** [comment]
Hi @snake14 
As I was saying before. I'm on the Cloud Version - 4.12
And I don't see a "System Check" option in the Diagnostic section...
![image](https://user-images.githubusercontent.com/46717153/195829503-6b8750cb-2170-468f-a5aa-683c83a8a460.png)

**Comment by snake14** [comment]
@lneuville Sorry about that. I'm not very familiar with the cloud configuration yet. Are you seeing any errors in your log when you try to rename a variable and the issue occurs? Since I can't reproduce the issue, I need more information. Any recommendations @AltamashShaikh ?
